acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: azure-acend
      replicaCount: 1
      image:
        repository: quay.io/acend/terraform-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "azure-acend"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: terraform-training
        domain: training.acend.ch
    - 
      name: azure-puzzle
      replicaCount: 1
      image:
        repository: quay.io/acend/terraform-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "azure-puzzle"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        useDefaultSecret: true
        appname: terraform-azure
        domain: k8s.puzzle.ch



nameOverride: "acend-terraform"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
