acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: azure-acend
      replicaCount: 2
      image:
        repository: quay.io/acend/terraform-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-azure-acend"
      ingress:
        secretOverride: acend-wildcard
        appname: terraform-azure
        domain: training.acend.ch
    - 
      name: aws-acend
      replicaCount: 2
      image:
        repository: quay.io/acend/terraform-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-aws-acend"
      ingress:
        secretOverride: acend-wildcard
        appname: terraform-aws
        domain: training.acend.ch
    - 
      name: gcp-acend
      replicaCount: 2
      image:
        repository: quay.io/acend/terraform-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-gcp-acend"
      ingress:
        secretOverride: acend-wildcard
        appname: terraform-gcp
        domain: training.acend.ch




nameOverride: "acend-terraform"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
